version: '3.6'

services:
  public-afcoma-prod:
    container_name: public-afcoma-prod
    image: public-afcoma-prod:v0.0.34-prod
    restart: always
    environment:
      - ENV=prod
    build:
      context: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.public-afcoma-prod-https.rule=Host(`apolo.afcoma.com.mx`)
      - traefik.http.routers.public-afcoma-prod-https.entrypoints=https
      - traefik.http.routers.public-afcoma-prod-https.tls=true
      - traefik.http.services.public-afcoma-prod-https.loadbalancer.server.port=80
    networks:
      - traefik_admin

networks:
  traefik_admin:
    external: true
